### ISSUE TITLE
Wayland support or documentation addition?

### ISSUE THREAD

**Issue by ajrichins** [YARC-Official/YARC-Launcher#41]
using ubuntu 22.04, gnome 42.9 with Wayland.
when running the yarc-launcher, I get this error
`(yarc-launcher:574632): GLib-GIO-ERROR **: 22:41:20.783: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing' `
`Trace/breakpoint trap (core dumped)`

seems like it might be a wayland support thing from a brief [search](https://github.com/Ultimaker/Cura/issues/12776), but I was wondering if y'all were already aware and had a fix other than using xorg or using the GDK_BACKEND=x11 flag solution found in said issue (both of which work btw).

Would be very sad if this is just another wayland/xorg compatibility bug, but if it is so, I'll add it to documentation

**Comment by EliteAsian123** [comment]
I seen you were in the Discord, but, essentially it's most likely a bug with Tauri, which is the library we use (similar to Electron).

**Comment by Soundtoxin** [comment]
I'm having an issue that may or may not be related. When I launch YARC Launcher from SteamOS's Game Mode (which is using the Gamescope Wayland compositor) on my Steam Deck it shows up as a blank white window and I can't seem to do anything. It launches fine in Desktop Mode (KDE Plasma, and according to `echo $XDG_SESSION_TYPE` they are running Plasma in X11 mode). My workaround for now is to launch the executables for Stable or Nightly that the launcher downloaded directly. I can add those as non-Steam games and they play fine in Game Mode. The downside being that if they ever get updated I need to go into Desktop Mode to get the launcher open and fetch a new version.
I've just updated to the new Nightly and tried again since the changelog mentioned possibly fixing this issue, but I didn't notice a change. Haven't got any useful terminal output due to the way it's launched.
Just spitballing here, but could some command line options be added to the launcher for updating the Stable and Nightly versions of YARG? Then I could run those over ssh from my PC and not have to leave Game Mode on the Deck.

**Comment by EliteAsian123** [comment]
> I'm having an issue that may or may not be related.

I'm not sure exactly how Steam Deck handles applications, but if it launches fine in Desktop Mode then it's probably a separate issue, unfortunately. 

> Just spitballing here, but could some command line options be added to the launcher for updating the Stable and Nightly versions of YARG? Then I could run those over ssh from my PC and not have to leave Game Mode on the Deck.

With how the launcher works, the majority of the updater is written in TypeScript, so the launcher would have to load properly in order for that to work, sadly.

**Comment by ajrichins** [comment]
@EliteAsian123 sorry it took so long, but it works now! thank you
